language: csharp
solution: Cli_Interface_Test.sln
os: windows
mono: none
addons:
  artifacts: true
script:
- choco install dotnetcore-sdk
- choco install 7zip.install
- dotnet --version
- dotnet restore
- dotnet build
- dir .\\bin\\Debug\\netcoreapp3.0
- 7z a -tzip release.zip .\\bin\\Debug\\netcoreapp3.0
- dir